name: Delete Old Workflows 删除旧工作流

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  Delete-Workflow-Archive:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        id: workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
